const LANG = {
  CODE_MAP: {
    Korean: "ko",
    English: "en",
    Khmer: "km",
    Nepal: "ne",
    Philiphine: "tl",
    Indonesia: "id",
    Vietnam: "vi",
    Bangladesh: "bn",
    Chinese: "zh",
    Uzbekistan: "uz",
    Srilanka: "si",
    Thailand: "th",
    MYANMAR: "my",
    Russia: "ru",
    Pakistan: "ur",
    Mongolian: "mn",
    日本語: "ja",
    LAOS: "lo",
  } as Record<string, string>,
  NAME_MAP: {
    한국: "한국어",
    캄보디아: "캄보디아어",
    네팔: "네팔어",
    필리핀: "필리핀어",
    인도네시아: "인도네시아어",
    베트남: "베트남어",
    방글라데시: "방글라데시어",
    우즈베키스탄: "우즈베키스탄어",
    스리랑카: "스리랑카어",
    태국: "태국어",
    미얀마: "미얀마어",
    러시아: "러시아어",
    파키스탄: "파키스탄어",
    몽골: "몽골어",
    일본: "일본어",
    라오스: "라오스어",
  } as Record<string, string>,
};

export { LANG };
