const TRANS = {
  ABBREVIATIONS: {
    employer: "emp",
    signature: "sign",
    recommend: "recom",
    application: "app",
    administrator: "admin",
    consultation: "consult",
    operation: "oper",
    policy: "policy",
    opportunities: "opps",
    opportunity: "opp",
    management: "mgmt",
    manager: "mgr",
    service: "svc",
    request: "req",
    required: "req",
    message: "msg",
    notification: "noti",
    information: "info",
    history: "hist",
    change: "chg",
    password: "pw",
  } as Record<string, string>,
  STOP_WORDS: new Set([
    "the",
    "a",
    "an",
    "this",
    "that",
    "these",
    "those",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "has",
    "have",
    "had",
    "will",
    "shall",
    "may",
    "might",
    "can",
    "could",
    "would",
    "should",
    "to",
    "of",
    "for",
    "in",
    "on",
    "at",
    "by",
    "with",
    "about",
    "from",
    "please",
    "your",
    "my",
    "our",
    "their",
    "his",
    "her",
    "its",
    "we",
    "you",
    "i",
    "he",
    "she",
    "it",
    "they",
    "ll",
    "ve",
    "re",
    "m",
  ]),
};

export { TRANS };
